-- Update profiles for reputation system
ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS seller_rating float DEFAULT 0,
ADD COLUMN IF NOT EXISTS rating_count int DEFAULT 0,
ADD COLUMN IF NOT EXISTS completed_commissions int DEFAULT 0;

-- Create a secure bucket for commission files (Private)
INSERT INTO storage.buckets (id, name, public)
VALUES ('secure_uploads', 'secure_uploads', false)
ON CONFLICT (id) DO NOTHING;

-- Create a public bucket for watermarked previews
INSERT INTO storage.buckets (id, name, public)
VALUES ('public_previews', 'public_previews', true)
ON CONFLICT (id) DO NOTHING;

-- RLS for Secure Uploads (Strict)
CREATE POLICY "Sellers can upload to secure bucket"
ON storage.objects FOR INSERT
WITH CHECK ( bucket_id = 'secure_uploads' AND auth.uid() = owner );

CREATE POLICY "Sellers can view their own secure files"
ON storage.objects FOR SELECT
USING ( bucket_id = 'secure_uploads' AND auth.uid() = owner );

-- Note: We will need a way for Buyers to view the file AFTER payment. 
-- This is usually done via Signed URLs generated by the server, so no RLS policy needed for buyers here.

-- RLS for Public Previews (Open)
CREATE POLICY "Anyone can view previews"
ON storage.objects FOR SELECT
USING ( bucket_id = 'public_previews' );

CREATE POLICY "Sellers can upload previews"
ON storage.objects FOR INSERT
WITH CHECK ( bucket_id = 'public_previews' AND auth.uid() = owner );
